// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CodeValidator is an autogenerated mock type for the CodeValidator type
type CodeValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: key, code
func (_m *CodeValidator) Validate(key string, code string) error {
	ret := _m.Called(key, code)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
